### ISSUE TITLE
typo in the function's name?

### ISSUE THREAD

**Issue by keyboardAnt** [hrayrhar/nnlib#2]
(shouldn't it be `_parse_ celeba`?)

https://github.com/hrayrhar/nnlib/blob/909cb7abb3996bbbb3de99c3b4d434c6329bc0fa/nnlib/data_utils/base.py#L254

**Comment by hrayrhar** [comment]
Thanks @keyboardAnt, good catch. Yes the name should be `_parse_celeba` (though what we have now causes will cause no issues). Please let me know if you want to open a pull request, otherwise I will fix it.

**Comment by hrayrhar** [comment]
Oh, actually found out that I had fixed it some time ago. The master branch has it correct. Anyway, thanks for noticing it.
